INSERT INTO Account (ACCOUNTID, firstName, lastName, accountNumber) VALUES (1, 'John', 'Doe', '123456')
INSERT INTO Account (ACCOUNTID, firstName, lastName, accountNumber) VALUES (2, 'Jane', 'Doe', '234567')
INSERT INTO Account (ACCOUNTID, firstName, lastName, accountNumber) VALUES (3, 'Jim', 'Taylor', '345678')
INSERT INTO Transaction (TRANSACTIONID, name) VALUES (1, 'Biscuit tin from Woolworths')
INSERT INTO Transaction (TRANSACTIONID, name) VALUES (2, 'Mcdonalds')
INSERT INTO Transaction (TRANSACTIONID, name) VALUES (3, 'Soap')